const assert = require("assert");
global.localStorage = { store: {}, getItem(key) { return this.store[key] || null; }, setItem(key, value) { this.store[key] = value; }, removeItem(key) { delete this.store[key]; } };
const TaskManager = require("./tasks.js");
console.log("Starting Chronosphere Task Citadel Logic Tests...");
const tm = new TaskManager();
const first = tm.addTask("  Defeat the Dragon  ");
assert.strictEqual(first.text, "Defeat the Dragon");
assert(first.reward >= 5 && first.reward <= 9);
assert.strictEqual(tm.addTask("   "), null);
const second = tm.addTask("Map the ruins");
assert.notStrictEqual(first.id, second.id);
assert.deepStrictEqual(tm.getStats(), { total: 2, completed: 0, pending: 2, earned: 0 });
let reward = 0; tm.onTaskComplete = value => { reward = value; };
assert.strictEqual(tm.completeTask(first.id).completed, true);
assert.strictEqual(reward, first.reward);
assert.strictEqual(tm.completeTask(first.id), null);
assert.deepStrictEqual(tm.getStats(), { total: 2, completed: 1, pending: 1, earned: first.reward });
tm.clearCompleted();
assert.deepStrictEqual(tm.getStats(), { total: 1, completed: 0, pending: 1, earned: 0 });
tm.deleteTask(second.id);
assert.strictEqual(tm.getTasks().length, 0);
console.log("All logic tests passed successfully!");
